/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: commandmessage.proto */

#ifndef PROTOBUF_C_commandmessage_2eproto__INCLUDED
#define PROTOBUF_C_commandmessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Aaproto__CommandMessage Aaproto__CommandMessage;
typedef struct _Aaproto__CommandMessage__LedCommands Aaproto__CommandMessage__LedCommands;


/* --- enums --- */

typedef enum _Aaproto__CommandMessage__DeviceType {
  AAPROTO__COMMAND_MESSAGE__DEVICE_TYPE__CONTROLLER = 0,
  AAPROTO__COMMAND_MESSAGE__DEVICE_TYPE__LED = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(AAPROTO__COMMAND_MESSAGE__DEVICE_TYPE)
} Aaproto__CommandMessage__DeviceType;
typedef enum _Aaproto__CommandMessage__LedCommand {
  AAPROTO__COMMAND_MESSAGE__LED_COMMAND__CONFIG = 0,
  AAPROTO__COMMAND_MESSAGE__LED_COMMAND__SWITCH_ON = 1,
  AAPROTO__COMMAND_MESSAGE__LED_COMMAND__SWITCH_OFF = 2,
  AAPROTO__COMMAND_MESSAGE__LED_COMMAND__TOGGLE = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(AAPROTO__COMMAND_MESSAGE__LED_COMMAND)
} Aaproto__CommandMessage__LedCommand;
typedef enum _Aaproto__CommandMessage__LedStatus {
  AAPROTO__COMMAND_MESSAGE__LED_STATUS__CONFIGURED = 0,
  AAPROTO__COMMAND_MESSAGE__LED_STATUS__ON = 1,
  AAPROTO__COMMAND_MESSAGE__LED_STATUS__OFF = 2,
  AAPROTO__COMMAND_MESSAGE__LED_STATUS__UNKNOWN = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(AAPROTO__COMMAND_MESSAGE__LED_STATUS)
} Aaproto__CommandMessage__LedStatus;

/* --- messages --- */

struct  _Aaproto__CommandMessage__LedCommands
{
  ProtobufCMessage base;
  int64_t pin;
  char *location;
  Aaproto__CommandMessage__LedCommand ledcmd;
};
#define AAPROTO__COMMAND_MESSAGE__LED_COMMANDS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aaproto__command_message__led_commands__descriptor) \
    , 0, (char *)protobuf_c_empty_string, AAPROTO__COMMAND_MESSAGE__LED_COMMAND__CONFIG }


/*
 * [START messages]
 */
struct  _Aaproto__CommandMessage
{
  ProtobufCMessage base;
  Aaproto__CommandMessage__DeviceType device;
  size_t n_ledcmds;
  Aaproto__CommandMessage__LedCommands **ledcmds;
  /*
   *  google.protobuf.Timestamp TransactionTimestamp = 3;
   * "TransactionTimestamp":"2022-04-16T03:05:20Z"
   */
  char *transactiontimestamp;
};
#define AAPROTO__COMMAND_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aaproto__command_message__descriptor) \
    , AAPROTO__COMMAND_MESSAGE__DEVICE_TYPE__CONTROLLER, 0,NULL, (char *)protobuf_c_empty_string }


/* Aaproto__CommandMessage__LedCommands methods */
void   aaproto__command_message__led_commands__init
                     (Aaproto__CommandMessage__LedCommands         *message);
/* Aaproto__CommandMessage methods */
void   aaproto__command_message__init
                     (Aaproto__CommandMessage         *message);
size_t aaproto__command_message__get_packed_size
                     (const Aaproto__CommandMessage   *message);
size_t aaproto__command_message__pack
                     (const Aaproto__CommandMessage   *message,
                      uint8_t             *out);
size_t aaproto__command_message__pack_to_buffer
                     (const Aaproto__CommandMessage   *message,
                      ProtobufCBuffer     *buffer);
Aaproto__CommandMessage *
       aaproto__command_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aaproto__command_message__free_unpacked
                     (Aaproto__CommandMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Aaproto__CommandMessage__LedCommands_Closure)
                 (const Aaproto__CommandMessage__LedCommands *message,
                  void *closure_data);
typedef void (*Aaproto__CommandMessage_Closure)
                 (const Aaproto__CommandMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor aaproto__command_message__descriptor;
extern const ProtobufCMessageDescriptor aaproto__command_message__led_commands__descriptor;
extern const ProtobufCEnumDescriptor    aaproto__command_message__device_type__descriptor;
extern const ProtobufCEnumDescriptor    aaproto__command_message__led_command__descriptor;
extern const ProtobufCEnumDescriptor    aaproto__command_message__led_status__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_commandmessage_2eproto__INCLUDED */
