/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: responsemessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "responsemessage.pb-c.h"
void   aaproto__response_message__init
                     (Aaproto__ResponseMessage         *message)
{
  static const Aaproto__ResponseMessage init_value = AAPROTO__RESPONSE_MESSAGE__INIT;
  *message = init_value;
}
size_t aaproto__response_message__get_packed_size
                     (const Aaproto__ResponseMessage *message)
{
  assert(message->base.descriptor == &aaproto__response_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aaproto__response_message__pack
                     (const Aaproto__ResponseMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aaproto__response_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aaproto__response_message__pack_to_buffer
                     (const Aaproto__ResponseMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aaproto__response_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Aaproto__ResponseMessage *
       aaproto__response_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Aaproto__ResponseMessage *)
     protobuf_c_message_unpack (&aaproto__response_message__descriptor,
                                allocator, len, data);
}
void   aaproto__response_message__free_unpacked
                     (Aaproto__ResponseMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aaproto__response_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue aaproto__response_message__device_type__enum_values_by_number[2] =
{
  { "CONTROLLER", "AAPROTO__RESPONSE_MESSAGE__DEVICE_TYPE__CONTROLLER", 0 },
  { "LED", "AAPROTO__RESPONSE_MESSAGE__DEVICE_TYPE__LED", 1 },
};
static const ProtobufCIntRange aaproto__response_message__device_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex aaproto__response_message__device_type__enum_values_by_name[2] =
{
  { "CONTROLLER", 0 },
  { "LED", 1 },
};
const ProtobufCEnumDescriptor aaproto__response_message__device_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "aaproto.ResponseMessage.DeviceType",
  "DeviceType",
  "Aaproto__ResponseMessage__DeviceType",
  "aaproto",
  2,
  aaproto__response_message__device_type__enum_values_by_number,
  2,
  aaproto__response_message__device_type__enum_values_by_name,
  1,
  aaproto__response_message__device_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue aaproto__response_message__led_response_code__enum_values_by_number[2] =
{
  { "SUCCESS", "AAPROTO__RESPONSE_MESSAGE__LED_RESPONSE_CODE__SUCCESS", 0 },
  { "FAILED", "AAPROTO__RESPONSE_MESSAGE__LED_RESPONSE_CODE__FAILED", 1 },
};
static const ProtobufCIntRange aaproto__response_message__led_response_code__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex aaproto__response_message__led_response_code__enum_values_by_name[2] =
{
  { "FAILED", 1 },
  { "SUCCESS", 0 },
};
const ProtobufCEnumDescriptor aaproto__response_message__led_response_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "aaproto.ResponseMessage.LedResponseCode",
  "LedResponseCode",
  "Aaproto__ResponseMessage__LedResponseCode",
  "aaproto",
  2,
  aaproto__response_message__led_response_code__enum_values_by_number,
  2,
  aaproto__response_message__led_response_code__enum_values_by_name,
  1,
  aaproto__response_message__led_response_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue aaproto__response_message__led_status__enum_values_by_number[4] =
{
  { "CONFIGURED", "AAPROTO__RESPONSE_MESSAGE__LED_STATUS__CONFIGURED", 0 },
  { "ON", "AAPROTO__RESPONSE_MESSAGE__LED_STATUS__ON", 1 },
  { "OFF", "AAPROTO__RESPONSE_MESSAGE__LED_STATUS__OFF", 2 },
  { "UNKNOWN", "AAPROTO__RESPONSE_MESSAGE__LED_STATUS__UNKNOWN", 3 },
};
static const ProtobufCIntRange aaproto__response_message__led_status__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex aaproto__response_message__led_status__enum_values_by_name[4] =
{
  { "CONFIGURED", 0 },
  { "OFF", 2 },
  { "ON", 1 },
  { "UNKNOWN", 3 },
};
const ProtobufCEnumDescriptor aaproto__response_message__led_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "aaproto.ResponseMessage.LedStatus",
  "LedStatus",
  "Aaproto__ResponseMessage__LedStatus",
  "aaproto",
  4,
  aaproto__response_message__led_status__enum_values_by_number,
  4,
  aaproto__response_message__led_status__enum_values_by_name,
  1,
  aaproto__response_message__led_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor aaproto__response_message__field_descriptors[5] =
{
  {
    "Device",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Aaproto__ResponseMessage, device),
    &aaproto__response_message__device_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "DeviceNo",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Aaproto__ResponseMessage, deviceno),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Response",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Aaproto__ResponseMessage, response),
    &aaproto__response_message__led_response_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Status",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Aaproto__ResponseMessage, status),
    &aaproto__response_message__led_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "TransactionTimestamp",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Aaproto__ResponseMessage, transactiontimestamp),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aaproto__response_message__field_indices_by_name[] = {
  0,   /* field[0] = Device */
  1,   /* field[1] = DeviceNo */
  2,   /* field[2] = Response */
  3,   /* field[3] = Status */
  4,   /* field[4] = TransactionTimestamp */
};
static const ProtobufCIntRange aaproto__response_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor aaproto__response_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aaproto.ResponseMessage",
  "ResponseMessage",
  "Aaproto__ResponseMessage",
  "aaproto",
  sizeof(Aaproto__ResponseMessage),
  5,
  aaproto__response_message__field_descriptors,
  aaproto__response_message__field_indices_by_name,
  1,  aaproto__response_message__number_ranges,
  (ProtobufCMessageInit) aaproto__response_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
