/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: responsemessage.proto */

#ifndef PROTOBUF_C_responsemessage_2eproto__INCLUDED
#define PROTOBUF_C_responsemessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Aaproto__ResponseMessage Aaproto__ResponseMessage;


/* --- enums --- */

typedef enum _Aaproto__ResponseMessage__DeviceType {
  AAPROTO__RESPONSE_MESSAGE__DEVICE_TYPE__CONTROLLER = 0,
  AAPROTO__RESPONSE_MESSAGE__DEVICE_TYPE__LED = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(AAPROTO__RESPONSE_MESSAGE__DEVICE_TYPE)
} Aaproto__ResponseMessage__DeviceType;
typedef enum _Aaproto__ResponseMessage__LedResponseCode {
  AAPROTO__RESPONSE_MESSAGE__LED_RESPONSE_CODE__SUCCESS = 0,
  AAPROTO__RESPONSE_MESSAGE__LED_RESPONSE_CODE__FAILED = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(AAPROTO__RESPONSE_MESSAGE__LED_RESPONSE_CODE)
} Aaproto__ResponseMessage__LedResponseCode;
typedef enum _Aaproto__ResponseMessage__LedStatus {
  AAPROTO__RESPONSE_MESSAGE__LED_STATUS__CONFIGURED = 0,
  AAPROTO__RESPONSE_MESSAGE__LED_STATUS__ON = 1,
  AAPROTO__RESPONSE_MESSAGE__LED_STATUS__OFF = 2,
  AAPROTO__RESPONSE_MESSAGE__LED_STATUS__UNKNOWN = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(AAPROTO__RESPONSE_MESSAGE__LED_STATUS)
} Aaproto__ResponseMessage__LedStatus;

/* --- messages --- */

/*
 * [START messages]
 */
struct  _Aaproto__ResponseMessage
{
  ProtobufCMessage base;
  Aaproto__ResponseMessage__DeviceType device;
  int64_t deviceno;
  Aaproto__ResponseMessage__LedResponseCode response;
  Aaproto__ResponseMessage__LedStatus status;
  /*
   *  google.protobuf.Timestamp TransactionTimestamp = 3;
   * "TransactionTimestamp":"2022-04-16T03:05:20Z"
   */
  char *transactiontimestamp;
};
#define AAPROTO__RESPONSE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aaproto__response_message__descriptor) \
    , AAPROTO__RESPONSE_MESSAGE__DEVICE_TYPE__CONTROLLER, 0, AAPROTO__RESPONSE_MESSAGE__LED_RESPONSE_CODE__SUCCESS, AAPROTO__RESPONSE_MESSAGE__LED_STATUS__CONFIGURED, (char *)protobuf_c_empty_string }


/* Aaproto__ResponseMessage methods */
void   aaproto__response_message__init
                     (Aaproto__ResponseMessage         *message);
size_t aaproto__response_message__get_packed_size
                     (const Aaproto__ResponseMessage   *message);
size_t aaproto__response_message__pack
                     (const Aaproto__ResponseMessage   *message,
                      uint8_t             *out);
size_t aaproto__response_message__pack_to_buffer
                     (const Aaproto__ResponseMessage   *message,
                      ProtobufCBuffer     *buffer);
Aaproto__ResponseMessage *
       aaproto__response_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aaproto__response_message__free_unpacked
                     (Aaproto__ResponseMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Aaproto__ResponseMessage_Closure)
                 (const Aaproto__ResponseMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor aaproto__response_message__descriptor;
extern const ProtobufCEnumDescriptor    aaproto__response_message__device_type__descriptor;
extern const ProtobufCEnumDescriptor    aaproto__response_message__led_response_code__descriptor;
extern const ProtobufCEnumDescriptor    aaproto__response_message__led_status__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_responsemessage_2eproto__INCLUDED */
